### 3 bateaux qui se déplacent vers une même cible à partir de trois positions initiales différentes

# bat1:
#   nodeSimu: # Fait référence au nom du node executé
#     ros__parameters: # Attention, il y a deux "_"
#       init_pos:
#       - 1.0
#       - 0.0
#       - 0.0
#   nodeCible:
#     ros__parameters:
#       x_cible:
#       - 10.0
#       - 10.0

# bat2:
#   nodeSimu: # Fait référence au nom du node executé
#     ros__parameters: # Attention, il y a deux "_"
#       init_pos:
#       - -21.0
#       - 4.0
#       - -1.0
#   nodeCible:
#     ros__parameters:
#       x_cible:
#       - 10.0
#       - 10.0


# bat3:
#   nodeSimu: # Fait référence au nom du node executé
#     ros__parameters: # Attention, il y a deux "_"
#       init_pos:
#       - 15.0
#       - -1.0
#       - 8.0
#   nodeCible:
#     ros__parameters:
#       x_cible:
#       - 10.0
#       - 10.0

### 3 bateaux qui se déplacent vers 3 cibles différentes à partir de la meme position initiale

# bat1:
#   nodeSimu: # Fait référence au nom du node executé
#     ros__parameters: # Attention, il y a deux "_"
#       init_pos:
#       - 0.0
#       - 0.0
#       - 0.0
#   nodeCible:
#     ros__parameters:
#       x_cible:
#       - 10.0
#       - 10.0

# bat2:
#   nodeSimu: # Fait référence au nom du node executé
#     ros__parameters: # Attention, il y a deux "_"
#       init_pos:
#       - 0.0
#       - 0.0
#       - 0.0
#   nodeCible:
#     ros__parameters:
#       x_cible:
#       - -14.0
#       - 0.0


# bat3:
#   nodeSimu: # Fait référence au nom du node executé
#     ros__parameters: # Attention, il y a deux "_"
#       init_pos:
#       - 0.0
#       - 0.0
#       - 0.0
#   nodeCible:
#     ros__parameters:
#       x_cible:
#       - 0.0
#       - -14.0

### 3 bateaux qui se déplacent vers 3 cibles différentes à partir de 3 positions initiales différentes

bat1:
  nodeSimu: # Fait référence au nom du node executé
    ros__parameters: # Attention, il y a deux "_"
      init_pos:
      - 1.0
      - 0.0
      - 0.0
  nodeCible:
    ros__parameters:
      x_cible:
      - 10.0
      - 10.0

bat2:
  nodeSimu: # Fait référence au nom du node executé
    ros__parameters: # Attention, il y a deux "_"
      init_pos:
      - 21.0
      - 4.0
      - -1.0
  nodeCible:
    ros__parameters:
      x_cible:
      - -14.0
      - 0.0


bat3:
  nodeSimu: # Fait référence au nom du node executé
    ros__parameters: # Attention, il y a deux "_"
      init_pos:
      - 15.0
      - -1.0
      - 8.0
  nodeCible:
    ros__parameters:
      x_cible:
      - 0.0
      - -14.0